const ko = {
  // Navigation
  setup: '설정',
  overview: '개요',
  proxies: '프록시',
  rules: '규칙',
  connections: '연결',
  logs: '로그',

  // Common states and labels
  default: '기본값',
  skip: '건너뛰기',
  online: '온라인',
  offline: '오프라인',
  statusLabel: '상태',
  activeLabel: '활성화됨',
  availableLabel: '사용 가능',
  dragOrClickToAdd: '끌어다 놓거나 클릭하여 추가',
  addRow: '행 추가',
  connected: '연결됨',
  copy: '복사',

  // Shared labels and actions
  protocol: '프로토콜',
  host: '호스트',
  port: '포트',
  password: '비밀번호',
  submit: '제출',
  cancel: '취소',
  delete: '삭제',
  download: '다운로드',
  upload: '업로드',
  downloadSpeed: '다운로드 속도',
  uploadSpeed: '업로드 속도',
  memoryUsage: '메모리 사용량',
  noData: '데이터 없음',

  // Backend actions and feedback
  flushFakeIP: 'Fake IP 비우기',
  flushDNSCache: 'DNS 캐시 비우기',
  flushDNSCacheSuccess: 'DNS 캐시를 성공적으로 비웠습니다',
  flushFakeIPSuccess: 'Fake IP를 성공적으로 비웠습니다',
  flushSmartWeightsSuccess: '스마트 가중치를 성공적으로 비웠습니다',
  restartCoreSuccess: '코어를 성공적으로 재시작했습니다',
  reloadConfigsSuccess: '구성을 성공적으로 다시 불러왔습니다',
  updateGeoSuccess: 'Geo 데이터베이스를 성공적으로 업데이트했습니다',
  actionRunning: '{action} 중...',
  chains: '체인',
  outbound: '아웃바운드',
  proxyGroup: '프록시 그룹',
  sortBy: '정렬 기준',
  rule: '규칙',
  sourceIP: '소스 IP',
  activeConnections: '활성',
  closedConnections: '종료됨',
  allConnections: '전체',
  logLevel: '로그 레벨',
  logType: '로그 유형',

  // Connections, proxies, and rules pages
  twoColumnProxyGroup: '프록시 그룹 2열 배치',
  type: '유형',
  process: '프로세스',
  connectTime: '연결 시간',
  sourcePort: '소스 포트',
  destination: '확인된 주소',
  destinationType: '확인된 유형',
  geoip: 'GeoIP',
  geoipCountryDatabaseURL: 'GeoIP 국가 데이터베이스 URL',
  geoipASNDatabaseURL: 'GeoIP ASN 데이터베이스 URL',
  geoipDatabaseURLTip:
    '연결 IP의 GeoIP 정보(국가 / ASN)를 로컬에서 확인하는 데 사용됩니다. mmdb 파일은 이 URL에서 로드되어 브라우저에 캐시됩니다. 기본값을 사용하려면 비워두세요.',
  inboundUser: '인바운드 사용자',
  basic: '기본 정보',
  traffic: '트래픽',
  sourceAndDestination: '소스 및 목적지',
  rawData: '원시 데이터',
  geoInfo: 'GeoIP',
  dl: '다운로드',
  ul: '업로드',
  dlSpeed: '다운로드 속도',
  ulSpeed: '업로드 속도',
  settings: '설정',
  speedtestUrl: '속도 테스트 URL',
  speedtestTimeout: '속도 테스트 제한 시간',
  speedtestMode: '속도 테스트 모드',
  speedtestModeDashboard: '대시보드 제어',
  speedtestModeCore: '코어 제어',
  speedtestModeTip:
    '대시보드 제어 모드는 Selector, LoadBalance, Smart 그룹을 대시보드 구동 노드별 테스트 흐름으로 유지하고 노드별 진행 상황을 표시합니다. 코어 제어 모드는 코어 그룹 지연 시간 API를 호출하여 코어가 전체 그룹을 한 번에 테스트하도록 합니다.',
  connectionStyle: '연결 스타일',
  logStyle: '로그 스타일',
  ruleStyle: '규칙 스타일',
  card: '카드형',
  table: '테이블형',
  time: '시간',
  content: '내용',
  name: '이름',
  ruleCount: '규칙 수',
  hitCount: '일치 횟수',
  missCount: '누락 횟수',
  behavior: '동작',
  vehicleType: '차량 유형',
  customTableColumns: '테이블 열 사용자 정의',
  customCardLines: '카드 줄 사용자 정의',
  close: '닫기',
  appearance: '테마 설정',
  defaultTheme: '기본 테마',
  darkTheme: '다크 테마',
  proxyProvider: '프록시 공급자',
  ruleProvider: '규칙 공급자',
  expire: '만료 예정',
  noExpire: '만료 없음',
  updated: '업데이트됨',
  upgradeDashboard: '대시보드 업그레이드',
  reloadConfigs: '구성 다시 불러오기',
  updateConfigs: '구성 업데이트',
  updateConfigsSuccess: '구성을 성공적으로 업데이트했습니다',
  configFilePath: '구성 파일 경로',
  configFilePathPlaceholder: '절대 경로 입력 (예: /etc/mihomo/config.yaml)',
  configPayload: '구성 내용',
  configPayloadPlaceholder: '여기에 YAML 구성 내용을 붙여넣으세요...',
  forceUpdate: '강제 업데이트',
  or: '또는',
  defaultsort: '구성 순서',
  nameasc: '이름 오름차순',
  namedesc: '이름 내림차순',
  latencydesc: '지연 시간 내림차순',
  latencyasc: '지연 시간 오름차순',

  // Settings sections and dialogs
  language: '언어',
  automaticDisconnection: '노드 전환 시 자동 연결 끊기',
  backend: '백엔드',
  tunMode: 'TUN 모드',
  upgradeCore: '코어 업그레이드',
  upgradeCoreConfirm:
    '지금 코어를 업그레이드하시겠습니까? 코어가 재시작되며 프록시 서비스가 잠시 중단됩니다.',
  upgradeToRelease: '정식 안정 버전으로 업그레이드',
  upgradeToAlpha: 'Alpha 버전으로 업그레이드',
  updateGeoDatabase: 'GEO 데이터베이스 업데이트',
  truncateProxyName: '프록시 이름 자르기',
  disableProxiesPageTextSelect: '프록시 페이지에서 텍스트 선택 비활성화',
  sourceIPLabels: '소스 IP 라벨',
  resolveClientHostname: '소스 IP 호스트 이름 확인',
  proxyPreviewType: '프록시 미리보기 유형',
  auto: '자동',
  dots: '점 (Dots)',
  bar: '막대 (Bar)',

  // Settings page
  exportSettings: '설정 내보내기',
  importSettings: '설정 가져오기',
  dashboardSettings: '대시보드 설정',
  dashboardSettingsCore: '코어',
  dashboardSettingsJsonFile: 'JSON 파일',
  dashboardSettingsUrl: 'URL',
  autoSyncSettings: '설정 자동 동기화',
  uploadSettings: '코어에 설정 업로드',
  syncSettings: '코어에서 설정 동기화',
  deleteUploadedSettings: '코어에서 업로드된 설정 삭제',
  connectionSettings: '연결 설정',
  proxySettings: '프록시 설정',
  logSettings: '로그 설정',
  ruleSettings: '규칙 설정',
  connectionDetails: '연결 상세 정보',
  customTheme: '사용자 정의 테마',
  unavailableProxy: '사용 불가능한 프록시 숨기기',
  protocolTips:
    'HTTP 백엔드에 연결하려고 하지만 zashboard가 HTTPS를 통해 제공되고 있습니다. 이로 인해 연결 오류가 발생할 수 있습니다. 브라우저 설정에서 안전하지 않은 콘텐츠를 허용하거나 http://board.zash.run.place 와 같은 zashboard의 HTTP 버전을 사용하세요.',
  global: '글로벌 (GLOBAL)',
  direct: '직접 연결 (DIRECT)',
  lowLatencyDesc: '노란색 경계값',
  mediumLatencyDesc: '빨간색 경계값',
  fonts: '글꼴',
  emoji: '이모지',
  unauthorizedTip: '인증되지 않았습니다. 다시 로그인해 주세요.',
  restartCore: '코어 재시작',
  restartCoreConfirm:
    '지금 코어를 재시작하시겠습니까? 프록시 서비스가 잠시 중단되며 기존 연결이 끊어집니다.',
  checkCoreUpgrade: '코어 업그레이드 확인',
  autoUpgradeDashboard: '대시보드 자동 업그레이드',
  autoUpgradeCore: '코어 자동 업그레이드',
  secondaryPath: '하위 경로 (Secondary path)',
  secondaryPathTip: '경로가 있는 경우 "/"로 시작하고, 없으면 비워두세요.',
  logRetentionLimit: '로그 보존 제한',
  DNSQuery: 'DNS 조회',
  confirm: '확인',
  backendSwitched: '백엔드가 전환되었습니다',
  backendConnecting: '연결 중...',
  backendReachable: '연결됨',
  backendUnreachable: '연결 실패',
  switchToAnotherBackend: '다른 백엔드로 전환',
  autoSwitchBackend: '연결 가능한 첫 번째 백엔드로 전환',
  noReachableBackend: '연결 가능한 다른 백엔드가 없습니다.',

  // Connection diagnosis
  diagnosisUnauthorized: '잘못된 비밀번호: 백엔드에서 자격 증명을 거부했습니다.',
  diagnosisTimeout: '백엔드가 시간 내에 응답하지 않았습니다.',
  diagnosisBadEndpoint: '주소에 접근할 수 있지만 이 API가 아니거나 경로가 잘못되었습니다.',
  diagnosisOffline: '브라우저가 오프라인 상태입니다. 네트워크 연결을 확인하세요.',
  diagnosisCorsBlocked:
    '백엔드에 접근할 수 있지만 브라우저가 응답을 차단했습니다. 백엔드가 이 출처(CORS)를 허용하지 않습니다. 코어 구성에서 external-controller-cors를 설정하세요.',
  diagnosisMixedContent:
    '브라우저가 요청을 차단했습니다. HTTPS 페이지는 HTTP 백엔드에 접근할 수 없습니다. HTTP를 통해 대시보드를 열거나 HTTPS를 통해 API를 제공하세요.',
  diagnosisMixedContentOrUnreachable:
    '백엔드에 접근할 수 없거나, 백엔드가 실행 중인 경우 브라우저가 이 HTTPS 페이지의 HTTP 백엔드 접근을 차단했습니다. HTTP를 통해 대시보드를 열어보세요.',
  diagnosisUnreachable:
    '백엔드에 접근할 수 없습니다. 주소와 포트가 올바른지, 코어가 실행 중인지 확인하세요.',

  // Backend settings
  ipv6Test: 'IPv6 테스트',
  socksPort: 'SOCKS 포트',
  httpPort: 'HTTP 포트',
  mixedPort: '혼합(Mixed) 포트',
  redirPort: 'Redir 포트',
  tproxyPort: 'TProxy 포트',
  tableSize: '테이블 크기',
  proxyCardSize: '프록시 카드 크기',
  small: '작게',
  normal: '보통',
  large: '크게',

  // Overview page
  autoIPCheckWhenStart: '시작 시 IP 자동 확인',
  autoConnectionCheckWhenStart: '시작 시 연결 상태 자동 확인',
  networkInfo: '네트워크 정보',
  autoSwitchTheme: '테마 자동 전환',
  customBackgroundURL: '배경 화면',
  splitOverviewPage: '개요 페이지 분할',
  manageHiddenGroup: '숨겨진 그룹 관리',
  showProxyGroup: '프록시 그룹 표시',
  hideProxyGroup: '프록시 그룹 숨기기',
  manageHiddenGroupShortcutTip: '{shortcut} 키를 눌러 숨겨진 그룹 관리를 토글하세요',
  transparent: '투명도',
  proxyGroupIconSize: '프록시 그룹 아이콘 크기',
  proxyGroupIconMargin: '프록시 그룹 아이콘 여백',
  allowLan: 'LAN 접속 허용',
  proxyChainDirection: '프록시 체인 방향',
  showFullProxyChain: '전체 프록시 체인 표시',
  reverse: '역방향',
  sniffHost: '호스트 스니핑',
  ipScreenshotTip: '스크린샷을 찍을 때 IP를 숨겨주세요.',
  showStatisticsWhenSidebarCollapsed: '사이드바가 접혔을 때 통계 표시',
  totalConnections: '연결 통계',
  totalConnectionsTip:
    '대시보드가 열려 있는 동안 시작된 연결만 집계됩니다.\n추적 시작 시간: {statsStartTime}',
  manual: '수동',
  tableWidthMode: '테이블 너비 모드',
  testFailed: '테스트 실패',
  testFinishedTip: '{name}\n{number}/{total} 테스트 완료',
  testFinishedResultTip: '{name}\n테스트 완료: {success} 성공, {failed} 시간 초과',
  testFailedTip: '{name}\n테스트 실패',
  updateFinishedTip: '{number}개의 업데이트 완료',

  // Page controls and interaction
  independentLatencyTest: '독립적인 지연 시간 테스트',
  independentLatencyTestTip:
    '활성화하면 지연 시간 테스트 시 zashboard의 URL 설정 대신 구성 파일에 지정된 URL을 사용합니다. 지연 시간은 정책 그룹에 설정된 URL을 기반으로 독립적으로 표시됩니다.',
  search: '검색',
  searchProxyGroup: '프록시 그룹 검색',
  searchProxyNode: '프록시 노드 검색',
  proxySearchModeGlobal: '노드 검색',
  proxySearchModeGroup: '정책 그룹 검색',
  importing: '가져오는 중...',
  hideConnection: '연결 숨기기',
  showConnection: '연결 표시',
  hideConnectionRegex: '연결 숨기기 정규식',
  hideConnectionTip:
    '대소문자를 구분하지 않는 정규식을 사용하여 원하지 않는 연결을 일치시키고 숨길 수 있습니다.',
  hideLog: '로그 숨기기',
  showLog: '로그 표시',
  hideLogRegex: '로그 숨기기 정규식',
  hideLogTip: '대소문자를 구분하지 않는 정규식을 사용하여 원하지 않는 로그를 일치시키고 숨길 수 있습니다.',
  loadBalance: '부하 분산 (Load balancing)',
  label: '라벨',
  optional: '선택 사항',
  swipeInTabs: '스와이프로 탭 전환',
  swipeInPages: '스와이프로 페이지 전환',
  simpleCardPreset: '간단한 프리셋',
  detailedCardPreset: '상세한 프리셋',
  refresh: '새로고침',
  reset: '초기화',
  resetSettings: '설정 초기화',
  resetSettingsConfirm:
    '모든 대시보드 설정을 기본값으로 초기화하시겠습니까? 이 작업은 취소할 수 없습니다.',
  backgroundToneSwitchConfirm:
    '이 배경은 {theme} 테마와 더 잘 어울립니다. 전환하시겠습니까?',
  backgroundToneLightThemeLabel: '라이트 테마',
  backgroundToneDarkThemeLabel: '다크 테마',
  minProxyCardWidth: '프록시 카드 최소 너비',
  displayGlobalByMode: '모드에 따라 GLOBAL 표시',
  displaySelectedNode: '선택된 노드 표시',
  displayLatencyNumber: '지연 시간 숫자 표시',
  disconnectOnRuleDisable: '규칙이 비활성화될 때 매칭되는 연결 끊기',
  tipForFixed:
    '현재 정책 그룹이 현재 노드에 고정되어 있습니다. 속도 테스트를 실행하여 {type} 동작을 복원하세요.',
  remoteAddress: '원격 주소',
  save: '저장',
  moreDetails: '자세한 정보',
  moreSettings: '추가 설정',
  customIcon: '사용자 정의 아이콘',
  dropOrClickUpload: '이미지를 끌어다 놓거나 URL을 붙여넣으세요',
  disablePullToRefresh: '당겨서 새로고침 비활성화',
  disablePullToRefreshTip:
    '당겨서 새로고침 기능과 가상 스크롤 컴포넌트가 충돌할 수 있습니다. 스크롤할 때 지연이 발생하거나 실수로 새로고침이 트리거되는 경우 이 기능을 비활성화해 보세요.',
  keyboardShortcuts: '키보드 단축키',
  keyboardShortcutsTip:
    '입력창을 클릭한 후 키 또는 키 조합을 누르면 단축키가 설정됩니다. 지우려면 Backspace 또는 Delete 키를 누르세요.',
  keyboardShortcutPageName: '{name} 페이지',
  toggleSidebar: '사이드바 토글',
  switchToPreviousBackend: '이전 백엔드로 전환',
  switchToNextBackend: '다음 백엔드로 전환',
  keyboardShortcutsConflict:
    '중복된 단축키 감지됨: {keys}. 첫 번째 단축키만 적용됩니다.',
  resetKeyboardShortcuts: '단축키 초기화',
  pressAnyKey: '아무 키나 누르세요',
  displayAllFeatures: '모든 기능 표시',
  displayAllFeaturesTip:
    '현재 코어(honk)의 공식 빌드에서 지원하지 않는 기능을 포함하여 모든 기능을 표시합니다. 해당 기능을 지원하는 포크(Fork) 버전을 사용하는 경우 활성화해 보세요.',
  blurIntensity: '블러(흐림) 강도',
  scrollAnimationEffect: '스크롤 애니메이션 효과',

  // Import, export, and upgrade
  importFromFile: '파일에서 가져오기',
  importFromUrl: 'URL에서 가져오기',
  uploadSettingsSuccess: '설정을 성공적으로 업로드했습니다',
  uploadSettingsIconReflectListRemoved:
    '사용자 정의 아이콘 데이터가 너무 커서 업로드 중에 제거되었습니다. 크기를 줄인 후 다시 시도하세요.',
  syncSettingsSuccess: '설정을 성공적으로 동기화했습니다',
  syncSettingsConfirm:
    '백엔드에 저장된 설정이 다음 로컬 설정을 덮어씁니다:\n\n{keys}\n\n적용하시겠습니까?',
  importSettingsConfirm:
    '가져온 설정이 다음 로컬 설정을 덮어씁니다:\n\n{keys}\n\n적용하시겠습니까?',
  dontAskAgainAlwaysApply: '다시 묻지 않고 항상 적용',
  confirmBeforeOverride: '로컬 설정을 덮어쓰기 전에 확인',
  deleteUploadedSettingsSuccess: '업로드된 설정을 성공적으로 삭제했습니다',
  deleteUploadedSettingsConfirm:
    '백엔드에 업로드된 설정을 정말로 삭제하시겠습니까? 이 작업은 취소할 수 없습니다.',
  upgradeSuccess: '업그레이드 성공',
  numberOfChartsInSidebar: '사이드바의 차트 개수',
  flushSmartWeights: '스마트 가중치 초기화',
  IPInfoAPI: 'IP 정보 API',
  IPInfoAPITip:
    '이 API는 연결 상세 정보 및 zashboard의 DNS 조회 기능에서 IP 지오로케이션(위치 정보)을 조회하는 데 사용됩니다. IP 확인 및 지구본 기능은 자체 API 설정을 사용합니다.',
  general: '일반',
  groupProxiesByProvider: '공급자별 프록시 그룹화',
  useSmartGroupSort: '사용 빈도순으로 스마트 그룹 정렬',
  all: '전체',
  autoDisconnectIdleUDP: '유휴 UDP 연결 자동 끊기',
  autoDisconnectIdleUDPTime: 'UDP 유휴 시간',
  autoDisconnectIdleUDPTip:
    '활성화하면 zashboard를 열 때 설정된 시간보다 오랫동안 유휴 상태였던 UDP 연결을 종료합니다. 자동으로 끊어지지 않는 UDP 연결을 정리하는 데 도움이 됩니다.',
  connectionTopology: '연결 토폴로지',
  applyConnectionFilter: '연결 필터 적용',
  topologyPause: '토폴로지 업데이트 일시정지',
  topologyResume: '토폴로지 업데이트 재개',
  topologyExpand: '토폴로지 뷰 확대',
  topologyCollapse: '토폴로지 뷰 복원',
  editBackend: '백엔드 편집',
  editBackendTitle: '백엔드 구성 편집',
  addBackend: '백엔드 추가',
  manageBackends: '백엔드 관리',
  noBackendYet: '아직 등록된 백엔드가 없습니다',
  backendConnectionFailed: '백엔드 연결에 실패했습니다. 구성을 확인해 주세요.',
  backendConfigSaved: '백엔드 구성을 성공적으로 저장했습니다',
  saveFailed: '저장 실패',
  checking: '확인 중...',
  copySuccess: '성공적으로 복사되었습니다',
  importFromBackendTip:
    '기본 ./zashboard-settings.json 경로는 ui 폴더 내에 있습니다. ui 폴더가 존재하고 구성 파일이 포함되어 있는지 확인하세요.',
  importFailed: '가져오기 실패, URL을 확인해 주세요: {url}',
  autoImportFromUrl: '자동 가져오기',
  autoImportFromUrlTip:
    '활성화하면 zashboard를 열 때 URL에서 설정을 자동으로 가져옵니다. 해시(Hash)가 마지막으로 가져온 해시와 다르면 설정을 다시 가져오고 페이지를 새로고침합니다.',
  getting: '가져오는 중...',
  mmdbSizeTip: 'MMDB 형식의 GEO 파일을 사용하는 경우 이 숫자는 0이 됩니다.',
  displayFinalOutbound: '최종 아웃바운드 노드 표시',
  groupTestUrls: '그룹 테스트 URL',
  groupTestUrlsTip:
    '대시보드에서 트리거되는 수동 테스트의 경우 URL 우선순위는 다음과 같습니다: 여기에 설정된 URL > 구성 파일의 URL > 글로벌 테스트 URL. UrlTest/Fallback과 같은 그룹의 경우 여전히 구성 파일의 URL을 수정해야 하므로, 이 설정은 주로 Selector 시나리오에 권장됩니다.',
  groupName: '그룹 이름',
  unknown: '알 수 없음',
  sourceIPAddress: '소스 IP 주소',
  ruleMatch: '규칙 일치',
  proxyChainEntry: '프록시 체인 진입점',
  proxyChainExit: '프록시 체인 출구',
  nodeType: '노드 유형',
  connectionCount: '연결 수',
  zashboardSettings: '대시보드 설정',
  backendSettings: '백엔드 설정',
  generalSettings: '일반 설정',
  overviewSettings: '개요 설정',
  overviewCardSettings: '카드 설정',
  chartsCard: '차트 카드',
  networkCard: '네트워크 카드',
  providerTrafficOverview: '공급자별 트래픽 개요',
  topologyCharts: '토폴로지 차트',
  earthGlobeCard: '글로벌 연결 지도',
  earthGlobeTitle: '글로벌 연결 지도',
  earthVisualStyle: '지구본 스타일',
  earthVisualStyle_space: '우주',
  earthVisualStyle_flat: '평면',
  earthOriginAPI: '공용 IP 서비스',
  earthLocalIP: '로컬 IP',
  earthToggleIP: '로컬 IP 표시/숨기기',
  earthHideCityLabels: '도시 이름 숨기기',
  earthShowCityLabels: '도시 이름 표시',
  earthPauseRotation: '지구본 회전 일시정지',
  earthResumeRotation: '지구본 회전 재개',
  earthExpand: '지구본 확대',
  earthCollapse: '지구본 복원',
  earthConnectionLine: '연결 경로',
  earthDatabaseChecking: '로컬 도시 데이터베이스 확인 중…',
  earthDatabaseLoading: '캐시된 도시 데이터베이스 로드 중…',
  earthDatabaseConsentTitle: '로컬 도시 데이터베이스를 다운로드하시겠습니까?',
  earthDatabaseConsent:
    '연결 엔드포인트 정보는 브라우저 내부에서 처리됩니다. DB-IP City Lite는 다운로드에 약 {download}, 압축 해제 후 로컬 저장소에 약 {stored}의 용량이 필요합니다.',
  earthDatabaseCacheRecovered:
    '손상된 캐시 데이터베이스를 제거했습니다. 위치 조회를 복원하려면 깨끗한 사본을 다시 다운로드하세요.',
  earthDatabaseDownload: '데이터베이스 다운로드',
  earthDatabaseLearnMore: 'DB-IP City Lite 정보',
  earthDatabaseDownloading: '도시 데이터베이스 다운로드 중',
  earthDatabaseError_space: '도시 데이터베이스를 저장하기 위한 브라우저 저장 공간이 부족합니다.',
  earthDatabaseError_network: '도시 데이터베이스를 다운로드할 수 없습니다.',
  earthDatabaseError_decompress: '도시 데이터베이스 압축을 해제할 수 없습니다.',
  earthDatabaseError_invalid: '다운로드한 도시 데이터베이스가 유효하지 않습니다.',
  earthDatabaseError_storage: '도시 데이터베이스를 브라우저 저장소에 저장할 수 없습니다.',
  earthDatabaseError_unsupported: '이 브라우저는 도시 데이터베이스 압축 해제를 지원하지 않습니다.',
  earthDatabaseError_unknown: '도시 데이터베이스를 로드할 수 없습니다.',
  earthOriginError: '로컬 공용 IP를 감지할 수 없습니다. 연결 위치를 찾으려면 다시 시도하세요.',
  earthNoConnections: '활성 연결 없음',
  earthNoLocatedConnections: '위치를 찾을 수 있는 활성 연결 엔드포인트가 없습니다',
  earthEndpointRole: '역할',
  earthTopDownloadedHosts: '다운로드 상위 5개 호스트',
  earthRole_origin: '로컬 기기',
  earthRole_destination: '목적지',
  earthRendererError: '이 브라우저에서는 3D 렌더링을 사용할 수 없습니다.',
  retry: '다시 시도',
  connectionHistory: '연결 기록',
  ruleHitCountCard: '규칙 일치/누락 통계',
  honkStatsCard: 'honk 런타임 통계',
  honkStatsOutbounds: '아웃바운드',
  honkStatsActiveConns: '활성',
  honkStatsErrors: '오류',
  latency: '지연 시간',
  icon: '아이콘',
  settingsMenuGeneral: '일반',
  settingsMenuBackend: '백엔드',
  settingsMenuProxies: '프록시',
  settingsMenuConnections: '연결',
  settingsMenuOverview: '개요',
  settingsDescriptionGeneral: '테마, 앱 업데이트, 데이터 소스 및 상호작용 기본 설정',
  settingsDescriptionOverview: '개요 카드, 시작 시 확인 및 데스크톱 사이드바',
  settingsDescriptionBackend: '활성 백엔드, 코어 유지관리 및 네트워크 리스너',
  settingsDescriptionProxies: '지연 시간 테스트, 프록시 그룹 표시 및 아이콘',
  settingsDescriptionConnections: '연결 표시, 테이블 옵션 및 클라이언트 식별',
  settingsCategory: '설정 카테고리',
  searchSettings: '설정 검색',
  noSettingsFound: '일치하는 설정이 없습니다',
  hiddenSearchResults: '일치하는 숨겨진 설정 {count}개',
  noVisibleSettingsCategories: '표시되는 카테고리가 없습니다. 설정 사용자 정의에서 복원하세요.',
  customize: '사용자 정의',
  customizeSettingsPage: '설정 사용자 정의',
  customizeSettingsDescription:
    '표시할 카테고리 및 설정을 선택하고 카테고리 순서를 변경합니다.',
  back: '뒤로',
  clear: '지우기',
  settingsSectionApplication: '앱 및 업데이트',
  settingsSectionNetworkData: '네트워크 및 데이터 소스',
  settingsSectionInteraction: '상호작용 및 단축키',
  settingsSectionCardsLayout: '카드 및 레이아웃',
  settingsSectionStartupChecks: '시작 시 확인',
  settingsSectionDesktopSidebar: '데스크톱 사이드바',
  settingsSectionCurrentBackend: '현재 백엔드',
  settingsSectionCoreOperations: '코어 유지관리',
  settingsSectionNetworkListening: '네트워크 리스너',
  settingsSectionCoreUpdates: '코어 업데이트',
  settingsSectionDiagnostics: '진단',
  settingsSectionProxyDisplay: '그룹 및 표시',
  settingsSectionProxyAdvanced: '아이콘 및 고급 설정',
  settingsSectionConnectionDisplay: '표시',
  settingsSectionClientIdentity: '클라이언트 식별 및 라벨',
  ports: '포트 목록',
  actions: '작업',
  showAllPreset: '전체 표시',
  minimalPreset: '최소 보기',
  moveUp: '위로 이동',
  moveDown: '아래로 이동',
  aggregateBy: '그룹화 기준',
  aggregateBySourceIP: '소스 IP별',
  aggregateByDestination: '목적지별',
  aggregateByProcess: '프로세스별',
  aggregateByOutbound: '아웃바운드별',
  aggregateByProxyGroup: '프록시 그룹별',
  totalTraffic: '전체 트래픽',
  total: '합계',
  clearConnectionHistory: '연결 기록 지우기',
  clearConnectionHistoryConfirm:
    '모든 연결 기록 데이터를 지우시겠습니까? 이 작업은 취소할 수 없습니다.',
  clearConnectionHistorySuccess: '연결 기록 데이터를 성공적으로 지웠습니다',
  autoCleanupInterval: '자동 정리 주기',
  autoCleanupIntervalWeek: '매주',
  autoCleanupIntervalMonth: '매달',
  autoCleanupIntervalQuarter: '분기별',
  autoCleanupIntervalNever: '안 함',
  remainingTraffic: '남은 트래픽',
  ruleHitCount: '일치: {count}회',
  ruleLastHit: '마지막 일치: {time}',
  ruleMissCount: '누락: {count}회',
  ruleLastMiss: '마지막 누락: {time}',

  // Smart Core
  RarelyUsed: '거의 사용되지 않음',
  OccasionalUsed: '가끔 사용됨',
  MostUsed: '가장 많이 사용됨',

  // Proxy folders
  proxyFolderMode: '프록시 폴더 모드',
  folderModeAuto: '자동',
  folderModeOn: '켜짐',
  folderModeOff: '꺼짐',
  folder_all: '전체',
  folder_uncategorized: '미분류',
  folder_manage: '폴더 관리',
  folder_builtin_strategy: '전략 (Strategy)',
  folder_builtin_nodes: '노드',
  folder_name: '폴더 이름',
  folder_new_placeholder: '새 폴더 이름',
  folder_rules: '자동 규칙',
  folder_rule_auto: '자동',
  folder_rule_regex: '정규식',
  folder_rule_exclude_regex: '제외 정규식',
  folder_auto_hasGroup: '하위 그룹 포함',
  folder_auto_nodeOnly: '노드만 포함',
  folder_add_rule: '규칙 추가',
  folder_manual_includes: '수동으로 포함됨',
  folder_filter_placeholder: '프록시 그룹 필터링',
  folder_preview: '자동 매칭된 그룹',
  folder_no_matches: '매칭된 그룹 없음',
  folder_delete_confirm: '"{name}" 폴더를 삭제하시겠습니까?',
}

export type LANG_MESSAGE = typeof ko
export default ko