const ko = {
  // Navigation
  setup: '설정',
  overview: '개요',
  proxies: '프록시',
  rules: '규칙',
  connections: '연결',
  logs: '로그',
  tools: '도구',
  tailscale: 'Tailscale',
  terminal: '터미널',

  // Backend type
  default: '기본값',
  backendType: '백엔드 유형',
  clashApi: 'Clash API',
  singboxApi: 'sing-box API',
  singboxConnectionFailed: 'sing-box 네이티브 API 연결에 실패했습니다',
  skip: '건너뛰기',

  // Tools page
  networkQuality: '네트워크 품질',
  stunTest: 'STUN 테스트',
  startTest: '테스트 시작',
  cancelTest: '테스트 취소',
  serverField: '서버',
  externalAddress: '외부 주소',
  natMapping: 'NAT 매핑',
  natFiltering: 'NAT 필터링',
  natTypeDetection: 'NAT 유형 감지',
  idleLatency: '유휴 지연 시간',
  downloadRPM: '다운로드 RPM',
  uploadRPM: '업로드 RPM',
  elapsed: '경과 시간',
  results: '결과',
  http3: 'HTTP/3',
  maxRuntime: '최대 실행 시간',
  startTime: '시작 시간',
  notSupportedByServer: '서버에서 지원하지 않음',
  configURL: '구성 URL',
  serial: '시리얼',
  accuracyHigh: '높음',
  accuracyMedium: '중간',
  accuracyLow: '낮음',
  fetchingConfiguration: '구성 가져오는 중...',
  binding: '바인딩 중...',

  // Tailscale page
  exitNode: '출구 노드 (Exit node)',
  ping: '핑',
  logout: '로그아웃',
  online: '온라인',
  offline: '오프라인',
  peers: '피어',
  noEndpoints: 'Tailscale 엔드포인트 없음',
  backendState: '상태',
  statusLabel: '상태',
  thisDevice: '이 기기',
  networkLabel: '네트워크',
  expired: '만료됨',
  connectViaSSH: 'SSH를 통해 연결',
  disabledLabel: '비활성화됨',
  directConnection: '직접 연결',
  derpRelayed: 'DERP 중계 연결',
  sharedIn: '공유됨',
  addresses: '주소',
  hostnameLabel: '호스트 이름',
  osLabel: 'OS',
  keyExpiry: '키 만료',
  lastSeen: '마지막 확인',
  detailsLabel: '상세 정보',
  authURL: '인증 URL',
  showAuthQR: '인증 URL QR 코드 표시',
  derpRegion: 'DERP 지역',
  endpointLabel: '엔드포인트',
  activeLabel: '활성화됨',
  availableLabel: '사용 가능',
  sshConfiguration: 'SSH 구성',
  terminalType: '터미널 유형',
  rememberSSHOptions: 'SSH 옵션 기억하기',
  editSSHConfiguration: 'SSH 구성 편집',
  connected: '연결됨',
  notConnected: '연결되지 않음',
  copy: '복사',
  yes: '예',

  // Terminal page
  peer: '피어',
  username: '사용자 이름',
  connect: '연결',
  sessionClosed: '세션이 종료되었습니다',
  newSession: '새 세션',
  paste: '붙여넣기',
  terminalKeys: '터미널 키',
  peerNotFound: '피어를 찾을 수 없습니다',
  connecting: '연결 중...',
  disconnect: '연결 끊기',
  sessionExited: '세션이 코드 {code}로 종료되었습니다',
  signalSuffix: '(시그널 {signal})',
  streamEnded: '스트림이 상태 {code}로 종료되었습니다',
  terminalSettings: '터미널 설정',
  terminalThemeLight: '테마 (라이트)',
  terminalThemeDark: '테마 (다크)',
  fontFamily: '글꼴 패밀리',
  fontSize: '글꼴 크기',
  defaultFont: '기본값',

  // USB/IP
  usbip: 'USB/IP',
  usbipNoServer: 'usbip-server를 찾을 수 없습니다',
  usbipServerTagged: 'USB/IP: {tag}',
  usbipDevices: '기기 목록',
  usbipConnectDevice: '기기 연결',
  usbipAuthorizedDevices: '인증된 기기',
  usbipOtherDevice: '기타 기기…',
  usbipDetach: '분리',
  usbipPickDeviceHint: '이 usbip-server를 통해 공유할 USB 기기를 선택하세요.',
  usbipNoDevicesShared: '아직 공유된 기기가 없습니다.',
  usbipInsecureContext:
    'WebUSB는 보안 컨텍스트(Secure Context)가 필요합니다. localhost 또는 HTTPS를 통해 대시보드를 열어주세요.',
  usbipUnsupportedBrowser:
    '기기를 제공하려면 Chromium 기반 브라우저에서 대시보드를 사용하거나, macOS 또는 Android의 sing-box 그래픽 클라이언트를 사용하세요.',
  usbipClaimBlockedClass:
    '“{label}”을(를) 공유할 수 없습니다: 브라우저가 이 기기의 인터페이스 클래스(예: HID, 스토리지, 오디오 또는 비디오) 공유를 차단합니다.',
  usbipClaimBlockedBusy:
    '“{label}”을(를) 공유할 수 없습니다: 다른 프로그램이나 드라이버가 사용 중입니다. 기기를 사용하는 프로그램을 닫고 다시 시도하세요.',
  usbipStateAttaching: '연결 중...',
  usbipStateReady: '준비 완료',
  usbipStateError: '오류',
  usbipStateIdle: '유휴 상태',
  usbipStateAttached: '연결됨',
  usbipStateUnavailable: '사용 불가',
  usbipIdentity: 'ID',
  usbipProduct: '제품',
  usbipSerialNumber: '일련번호',
  usbipVersion: '버전',
  usbipConnection: '연결',
  usbipBusId: '버스 ID',
  usbipBackend: '백엔드',
  usbipSpeed: '속도',
  usbipBusDevice: '버스 / 기기',
  usbipClassInterfaces: '클래스 및 인터페이스',
  usbipDeviceClass: '기기 클래스',
  usbipDefinedAtInterface: '인터페이스 레벨에서 정의됨',
  usbipConfigurations: '구성',
  usbipInterfaceN: '인터페이스 {n}',

  // Shared labels and actions
  protocol: '프로토콜',
  host: '호스트',
  port: '포트',
  password: '비밀번호',
  submit: '확인',
  cancel: '취소',
  delete: '삭제',
  download: '다운로드',
  upload: '업로드',
  downloadSpeed: '다운로드 속도',
  uploadSpeed: '업로드 속도',
  memoryUsage: '메모리 사용량',
  goroutines: '고루틴 (Goroutines)',
  noData: '데이터 없음',

  // Backend actions and feedback
  flushFakeIP: 'Fake IP 비우기',
  flushDNSCache: 'DNS 캐시 비우기',
  flushDNSCacheSuccess: 'DNS 캐시를 성공적으로 비웠습니다',
  flushFakeIPSuccess: 'Fake IP를 성공적으로 비웠습니다',
  flushSmartWeightsSuccess: '스마트 가중치를 성공적으로 초기화했습니다',
  restartCoreSuccess: '코어를 성공적으로 재시작했습니다',
  reloadConfigsSuccess: '구성을 성공적으로 다시 불러왔습니다',
  updateGeoSuccess: 'Geo 데이터베이스를 성공적으로 업데이트했습니다',
  chains: '체인',
  outbound: '아웃바운드',
  sortBy: '정렬 기준',
  rule: '규칙',
  sourceIP: '소스 IP',
  activeConnections: '연결됨',
  closedConnections: '종료됨',
  logLevel: '로그 레벨',
  logType: '로그 유형',

  // Connections, proxies, and rules pages
  twoColumnProxyGroup: '프록시 그룹 2열 배치',
  type: '유형',
  process: '프로세스',
  connectTime: '연결 시간',
  sourcePort: '소스 포트',
  destination: '확인된 주소',
  destinationType: '확인된 유형',
  inboundUser: '인바운드 사용자',
  outboundType: '아웃바운드 유형',
  fromOutbound: '아웃바운드 출처',
  basic: '기본 정보',
  traffic: '트래픽',
  sourceAndDestination: '소스 및 목적지',
  rawData: '원시 데이터',
  geoInfo: 'GeoIP',
  dl: '다운로드',
  ul: '업로드',
  dlSpeed: '다운로드 속도',
  ulSpeed: '업로드 속도',
  settings: '설정',
  speedtestUrl: '속도 테스트 URL',
  speedtestTimeout: '속도 테스트 제한 시간',
  speedtestMode: '속도 테스트 모드',
  speedtestModeDashboard: '대시보드 제어',
  speedtestModeCore: '코어 제어',
  speedtestModeTip:
    '대시보드 제어 모드는 Selector, LoadBalance, Smart 그룹을 대시보드 구동 노드별 테스트 흐름으로 유지하고 노드별 진행 상황을 표시합니다. 코어 제어 모드는 코어 그룹 지연 시간 API를 호출하여 코어가 전체 그룹을 한 번에 테스트하도록 합니다.',
  connectionStyle: '연결 스타일',
  card: '카드형',
  table: '테이블형',
  customTableColumns: '테이블 열 사용자 정의',
  customCardLines: '카드 줄 사용자 정의',
  close: '닫기',
  appearance: '테마 설정',
  defaultTheme: '기본 테마',
  darkTheme: '다크 테마',
  proxyProvider: '프록시 공급자',
  ruleProvider: '규칙 공급자',
  expire: '만료 예정',
  noExpire: '만료 없음',
  updated: '업데이트됨',
  upgradeDashboard: '대시보드 업그레이드',
  reloadConfigs: '구성 다시 불러오기',
  updateConfigs: '구성 업데이트',
  updateConfigsSuccess: '구성을 성공적으로 업데이트했습니다',
  configFilePath: '구성 파일 경로',
  configFilePathPlaceholder: '절대 경로 입력 (예: /etc/mihomo/config.yaml)',
  configPayload: '구성 내용',
  configPayloadPlaceholder: '여기에 YAML 구성 내용을 붙여넣으세요...',
  forceUpdate: '강제 업데이트',
  or: '또는',
  defaultsort: '구성 순서',
  nameasc: '이름 오름차순',
  namedesc: '이름 내림차순',
  latencydesc: '지연 시간 내림차순',
  latencyasc: '지연 시간 오름차순',

  // Settings sections and dialogs
  language: '언어',
  automaticDisconnection: '노드 전환 시 자동 연결 끊기',
  backend: '백엔드',
  tunMode: 'TUN 모드',
  upgradeCore: '코어 업그레이드',
  upgradeToRelease: '정식 안정 버전으로 업그레이드',
  upgradeToAlpha: 'Alpha 버전으로 업그레이드',
  updateGeoDatabase: 'GEO 데이터베이스 업데이트',
  truncateProxyName: '프록시 이름 자르기',
  disableProxiesPageTextSelect: '프록시 페이지에서 텍스트 선택 비활성화',
  sourceIPLabels: '소스 IP 라벨',
  proxyPreviewType: '프록시 미리보기 유형',
  auto: '자동',
  dots: '점 (Dots)',
  bar: '막대 (Bar)',

  // Settings page
  exportSettings: '설정 내보내기',
  importSettings: '설정 가져오기',
  dashboardSettings: '대시보드 설정',
  dashboardSettingsCore: '코어',
  dashboardSettingsJsonFile: 'JSON 파일',
  dashboardSettingsUrl: 'URL',
  autoSyncSettings: '설정 자동 동기화',
  uploadSettings: '코어에 설정 업로드',
  syncSettings: '코어에서 설정 동기화',
  deleteUploadedSettings: '코어에서 업로드된 설정 삭제',
  connectionSettings: '연결 설정',
  proxySettings: '프록시 설정',
  logSettings: '로그 설정',
  ruleSettings: '규칙 설정',
  connectionDetails: '연결 상세 정보',
  customTheme: '사용자 정의 테마',
  unavailableProxy: '사용 불가능한 프록시 숨기기',
  protocolTips:
    'HTTP 백엔드에 연결하려고 하지만 대시보드가 HTTPS를 통해 제공되고 있습니다. 이로 인해 연결 오류가 발생할 수 있습니다. 브라우저 설정에서 안전하지 않은 콘텐츠를 허용하거나 http://board.zash.run.place 와 같은 대시보드의 HTTP 버전을 사용하세요.',
  global: '글로벌 (GLOBAL)',
  direct: '직접 연결 (DIRECT)',
  lowLatencyDesc: '노란색 경계값',
  mediumLatencyDesc: '빨간색 경계값',
  fonts: '글꼴',
  emoji: '이모지',
  unauthorizedTip: '인증되지 않았습니다. 다시 로그인해 주세요.',
  restartCore: '코어 재시작',
  checkCoreUpgrade: '코어 업그레이드 확인',
  autoUpgradeDashboard: '대시보드 자동 업그레이드',
  autoUpgradeCore: '코어 자동 업그레이드',
  secondaryPath: '하위 경로 (Secondary path)',
  secondaryPathTip: '경로가 있는 경우 "/"로 시작하고, 없으면 비워두세요.',
  logRetentionLimit: '로그 보존 제한',
  DNSQuery: 'DNS 조회',
  currentBackendUnavailable:
    '현재 백엔드를 사용할 수 없습니다. 다른 백엔드로 전환하시겠습니까?',
  confirm: '확인',
  backendSwitchTo: '백엔드를 {backend}(으)로 전환했습니다',

  // Backend settings
  ipv6Test: 'IPv6 테스트',
  socksPort: 'SOCKS 포트',
  httpPort: 'HTTP 포트',
  mixedPort: '혼합(Mixed) 포트',
  redirPort: 'Redir 포트',
  tproxyPort: 'TProxy 포트',
  tableSize: '테이블 크기',
  proxyCardSize: '프록시 카드 크기',
  small: '작게',
  normal: '보통',
  large: '크게',

  // Overview page
  autoIPCheckWhenStart: '시작 시 IP 자동 확인',
  autoConnectionCheckWhenStart: '시작 시 연결 상태 자동 확인',
  networkInfo: '네트워크 정보',
  autoSwitchTheme: '테마 자동 전환',
  customBackgroundURL: '배경 화면',
  splitOverviewPage: '개요 페이지 분할',
  manageHiddenGroup: '숨겨진 그룹 관리',
  transparent: '투명도',
  proxyGroupIconSize: '프록시 그룹 아이콘 크기',
  proxyGroupIconMargin: '프록시 그룹 아이콘 여백',
  allowLan: 'LAN 접속 허용',
  proxyChainDirection: '프록시 체인 방향',
  showFullProxyChain: '전체 프록시 체인 표시',
  reverse: '역방향',
  sniffHost: '호스트 스니핑',
  ipScreenshotTip: '스크린샷을 찍을 때 IP를 숨겨주세요.',
  showStatisticsWhenSidebarCollapsed: '사이드바가 접혔을 때 통계 표시',
  totalConnections: '연결 통계',
  totalConnectionsTip:
    '대시보드가 열려 있는 동안 시작된 연결만 집계됩니다.\n추적 시작 시간: {statsStartTime}',
  manual: '수동',
  tableWidthMode: '테이블 너비 모드',
  testFailed: '테스트 실패',
  testFinishedTip: '{name}\n{number}/{total} 테스트 완료',
  testFinishedResultTip: '{name}\n테스트 완료: {success} 성공, {failed} 시간 초과',
  testFailedTip: '{name}\n테스트 실패',
  updateFinishedTip: '{number}개의 업데이트 완료',

  // Page controls and interaction
  independentLatencyTest: '독립적인 지연 시간 테스트',
  independentLatencyTestTip:
    '활성화하면 지연 시간 테스트 시 대시보드의 URL 설정 대신 구성 파일에 지정된 URL을 사용합니다. 지연 시간은 정책 그룹에 설정된 URL을 기반으로 독립적으로 표시됩니다.',
  search: '검색',
  searchProxyGroup: '프록시 그룹 검색',
  searchProxyNode: '프록시 노드 검색',
  proxySearchModeGlobal: '노드 검색',
  proxySearchModeGroup: '정책 그룹 검색',
  importing: '가져오는 중...',
  hideConnection: '연결 숨기기',
  showConnection: '연결 표시',
  hideConnectionRegex: '연결 숨기기 정규식',
  hideConnectionTip:
    '대소문자를 구분하지 않는 정규식을 사용하여 원하지 않는 연결을 일치시키고 숨길 수 있습니다.',
  hideLog: '로그 숨기기',
  showLog: '로그 표시',
  hideLogRegex: '로그 숨기기 정규식',
  hideLogTip: '대소문자를 구분하지 않는 정규식을 사용하여 원하지 않는 로그를 일치시키고 숨길 수 있습니다.',
  sameConnectionLogs: '동일한 연결의 로그',
  loadBalance: '부하 분산 (Load balancing)',
  label: '라벨',
  optional: '선택 사항',
  swipeInTabs: '스와이프로 탭 전환',
  swipeInPages: '스와이프로 페이지 전환',
  simpleCardPreset: '간단한 프리셋',
  detailedCardPreset: '상세한 프리셋',
  refresh: '새로고침',
  reset: '초기화',
  resetSettings: '설정 초기화',
  resetSettingsConfirm:
    '모든 대시보드 설정을 기본값으로 초기화하시겠습니까? 이 작업은 취소할 수 없습니다.',
  backgroundToneSwitchConfirm:
    '이 배경은 {theme} 테마와 더 잘 어울립니다. 전환하시겠습니까?',
  backgroundToneLightThemeLabel: '라이트 테마',
  backgroundToneDarkThemeLabel: '다크 테마',
  minProxyCardWidth: '프록시 카드 최소 너비',
  displayGlobalByMode: '모드에 따라 GLOBAL 표시',
  displaySelectedNode: '선택된 노드 표시',
  displayLatencyNumber: '지연 시간 숫자 표시',
  disconnectOnRuleDisable: '규칙이 비활성화될 때 매칭되는 연결 끊기',
  tipForFixed:
    '현재 정책 그룹이 현재 노드에 고정되어 있습니다. 속도 테스트를 실행하여 {type} 동작을 복원하세요.',
  remoteAddress: '원격 주소',
  save: '저장',
  moreDetails: '자세한 정보',
  moreSettings: '추가 설정',
  customIcon: '사용자 정의 아이콘',
  dropOrClickUpload: '이미지를 끌어다 놓거나 URL을 붙여넣으세요',
  disablePullToRefresh: '당겨서 새로고침 비활성화',
  disablePullToRefreshTip:
    '당겨서 새로고침 기능과 가상 스크롤 컴포넌트가 충돌할 수 있습니다. 스크롤할 때 지연이 발생하거나 실수로 새로고침이 트리거되는 경우 이 기능을 비활성화해 보세요.',
  keyboardShortcuts: '키보드 단축키',
  keyboardShortcutsTip:
    '입력창을 클릭한 후 키 또는 키 조합을 누르면 단축키가 설정됩니다. 지우려면 Backspace 또는 Delete 키를 누르세요.',
  keyboardShortcutPageName: '{name} 페이지',
  toggleSidebar: '사이드바 토글',
  switchToPreviousBackend: '이전 백엔드로 전환',
  switchToNextBackend: '다음 백엔드로 전환',
  openBackendSettings: '백엔드 설정 열기',
  keyboardShortcutsConflict:
    '중복된 단축키 감지됨: {keys}. 첫 번째 단축키만 적용됩니다.',
  resetKeyboardShortcuts: '단축키 초기화',
  pressAnyKey: '아무 키나 누르세요',
  displayAllFeatures: '모든 기능 표시',
  displayAllFeaturesTip:
    '공식 sing-box 버전에서 지원하지 않는 기능을 포함하여 모든 기능을 표시합니다. 일부 기능을 지원하는 sing-box의 포크(Fork) 버전을 사용하는 경우 이 기능을 활성화해 볼 수 있습니다.',
  blurIntensity: '블러(흐림) 강도',
  scrollAnimationEffect: '스크롤 애니메이션 효과',

  // Import, export, and upgrade
  importFromFile: '파일에서 가져오기',
  importFromUrl: 'URL에서 가져오기',
  uploadSettingsSuccess: '설정을 성공적으로 업로드했습니다',
  uploadSettingsIconReflectListRemoved:
    '사용자 정의 아이콘 데이터가 너무 커서 업로드 중에 제거되었습니다. 크기를 줄인 후 다시 시도하세요.',
  syncSettingsSuccess: '설정을 성공적으로 동기화했습니다',
  deleteUploadedSettingsSuccess: '업로드된 설정을 성공적으로 삭제했습니다',
  deleteUploadedSettingsConfirm:
    '백엔드에 업로드된 설정을 정말로 삭제하시겠습니까? 이 작업은 취소할 수 없습니다.',
  upgradeSuccess: '업그레이드 성공',
  numberOfChartsInSidebar: '사이드바의 차트 개수',
  flushSmartWeights: '스마트 가중치 초기화',
  IPInfoAPI: 'IP 정보 API',
  IPInfoAPITip:
    '이 API는 IP 확인 중 글로벌 노드 IP 정보를 조회하거나, 연결 상세 정보 및 대시보드의 DNS 조회 기능에서 IP 지오로케이션(위치 정보)을 조회하는 데 사용됩니다.',
  general: '일반',
  groupProxiesByProvider: '공급자별 프록시 그룹화',
  useSmartGroupSort: '사용 빈도순으로 스마트 그룹 정렬',
  all: '전체',
  autoDisconnectIdleUDP: '유휴 UDP 연결 자동 끊기',
  autoDisconnectIdleUDPTime: 'UDP 유휴 시간',
  autoDisconnectIdleUDPTip:
    '활성화하면 대시보드를 열 때 설정된 시간보다 오랫동안 유휴 상태였던 UDP 연결을 종료합니다. 자동으로 끊어지지 않는 UDP 연결을 정리하는 데 도움이 됩니다.',
  customGlobalNode: '사용자 정의 글로벌 노드',
  connectionTopology: '연결 토폴로지',
  editBackend: '백엔드 편집',
  editBackendTitle: '백엔드 구성 편집',
  selectBackend: '백엔드 선택',
  backendConnectionFailed: '백엔드 연결에 실패했습니다. 구성을 확인해 주세요.',
  backendConfigSaved: '백엔드 구성을 성공적으로 저장했습니다',
  saveFailed: '저장 실패',
  checking: '확인 중...',
  copySuccess: '성공적으로 복사되었습니다',
  importFromBackendTip:
    '기본 경로는 ui 폴더 내에 있습니다. ui 폴더가 존재하고 구성 파일이 포함되어 있는지 확인하세요.',
  importFailed: '가져오기 실패, URL을 확인해 주세요: {url}',
  autoImportFromUrl: '자동 가져오기',
  autoImportFromUrlTip:
    '활성화하면 대시보드를 열 때 URL에서 설정을 자동으로 가져옵니다. 해시(Hash)가 마지막으로 가져온 해시와 다르면 설정을 다시 가져오고 페이지를 새로고침합니다.',
  getting: '가져오는 중...',
  mmdbSizeTip: 'MMDB 형식의 GEO 파일을 사용하는 경우 이 숫자는 0이 됩니다.',
  displayFinalOutbound: '최종 아웃바운드 노드 표시',
  groupTestUrls: '그룹 테스트 URL',
  groupTestUrlsTip:
    '대시보드에서 트리거되는 수동 테스트의 경우 URL 우선순위는 다음과 같습니다: 여기에 설정된 URL > 구성 파일의 URL > 글로벌 테스트 URL. UrlTest/Fallback과 같은 그룹의 경우 여전히 구성 파일의 URL을 수정해야 하므로, 이 설정은 주로 Selector 시나리오에 권장됩니다.',
  groupName: '그룹 이름',
  unknown: '알 수 없음',
  sourceIPAddress: '소스 IP 주소',
  ruleMatch: '규칙 일치',
  proxyChainEntry: '프록시 체인 진입점',
  proxyChainExit: '프록시 체인 출구',
  nodeType: '노드 유형',
  connectionCount: '연결 수',
  zashboardSettings: '대시보드 설정',
  backendSettings: '백엔드 설정',
  generalSettings: '일반 설정',
  overviewSettings: '개요 설정',
  overviewCardSettings: '카드 설정',
  chartsCard: '차트 카드',
  networkCard: '네트워크 카드',
  providerTrafficOverview: '공급자별 트래픽 개요',
  topologyCharts: '토폴로지 차트',
  connectionHistory: '연결 기록',
  ruleHitCountCard: '규칙 일치/누락 통계',
  latency: '지연 시간',
  icon: '아이콘',
  settingsVisibility: '설정 표시 여부',
  settingsMenuGeneral: '일반',
  settingsMenuBackend: '백엔드',
  settingsMenuProxies: '프록시',
  settingsMenuConnections: '연결',
  settingsMenuOverview: '개요',
  ports: '포트 목록',
  actions: '작업',
  showAllPreset: '전체 표시',
  minimalPreset: '최소 보기',
  settingsPageTwoColumns: '2열 레이아웃',
  moveUp: '위로 이동',
  moveDown: '아래로 이동',
  aggregateBy: '그룹화 기준',
  aggregateBySourceIP: '소스 IP별',
  aggregateByDestination: '목적지별',
  aggregateByProcess: '프로세스별',
  aggregateByOutbound: '아웃바운드별',
  totalTraffic: '전체 트래픽',
  total: '합계',
  clearConnectionHistory: '연결 기록 지우기',
  clearConnectionHistoryConfirm:
    '모든 연결 기록 데이터를 지우시겠습니까? 이 작업은 취소할 수 없습니다.',
  clearConnectionHistorySuccess: '연결 기록 데이터를 성공적으로 지웠습니다',
  autoCleanupInterval: '자동 정리 주기',
  autoCleanupIntervalWeek: '매주',
  autoCleanupIntervalMonth: '매달',
  autoCleanupIntervalQuarter: '분기별',
  autoCleanupIntervalNever: '안 함',
  remainingTraffic: '남은 트래픽',
  ruleHitCount: '일치: {count}회',
  ruleLastHit: '마지막 일치: {time}',
  ruleMissCount: '누락: {count}회',
  ruleLastMiss: '마지막 누락: {time}',

  // Smart Core
  RarelyUsed: '거의 사용되지 않음',
  OccasionalUsed: '가끔 사용됨',
  MostUsed: '가장 많이 사용됨',

  // Proxy folders
  proxyFolderMode: '프록시 폴더 모드',
  folderModeAuto: '자동',
  folderModeOn: '켜짐',
  folderModeOff: '꺼짐',
  folder_all: '전체',
  folder_uncategorized: '미분류',
  folder_manage: '폴더 관리',
  folder_builtin_strategy: '전략 (Strategy)',
  folder_builtin_nodes: '노드',
  folder_name: '폴더 이름',
  folder_new_placeholder: '새 폴더 이름',
  folder_rules: '자동 규칙',
  folder_rule_auto: '자동',
  folder_rule_regex: '정규식',
  folder_rule_exclude_regex: '제외 정규식',
  folder_auto_hasGroup: '하위 그룹 포함',
  folder_auto_nodeOnly: '노드만 포함',
  folder_add_rule: '규칙 추가',
  folder_manual_includes: '수동으로 포함됨',
  folder_filter_placeholder: '프록시 그룹 필터링',
  folder_preview: '자동 매칭된 그룹',
  folder_no_matches: '매칭된 그룹 없음',
  folder_delete_confirm: '"{name}" 폴더를 삭제하시겠습니까?',
}

export type LANG_MESSAGE = typeof ko
export default ko